// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfoDId70UinkLUVBYM23faasKfwjZ2__M',
    appId: '1:108884990143:web:80376f72249aaeb6cd8e0a',
    messagingSenderId: '108884990143',
    projectId: 'smartspend-962d7',
    authDomain: 'smartspend-962d7.firebaseapp.com',
    storageBucket: 'smartspend-962d7.firebasestorage.app',
    measurementId: 'G-D6L2YDSNS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-F58eJPkX1iMUtBd5MkGpcm3PxCTR30',
    appId: '1:108884990143:android:819ee6f4523482fbcd8e0a',
    messagingSenderId: '108884990143',
    projectId: 'smartspend-962d7',
    storageBucket: 'smartspend-962d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_3eEAXTOv3lMKqBrciNs4Gr-VF1DINlI',
    appId: '1:108884990143:ios:00d87751df6389e0cd8e0a',
    messagingSenderId: '108884990143',
    projectId: 'smartspend-962d7',
    storageBucket: 'smartspend-962d7.firebasestorage.app',
    iosBundleId: 'com.example.smartSpend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_3eEAXTOv3lMKqBrciNs4Gr-VF1DINlI',
    appId: '1:108884990143:ios:00d87751df6389e0cd8e0a',
    messagingSenderId: '108884990143',
    projectId: 'smartspend-962d7',
    storageBucket: 'smartspend-962d7.firebasestorage.app',
    iosBundleId: 'com.example.smartSpend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfoDId70UinkLUVBYM23faasKfwjZ2__M',
    appId: '1:108884990143:web:10741f86c8611cb0cd8e0a',
    messagingSenderId: '108884990143',
    projectId: 'smartspend-962d7',
    authDomain: 'smartspend-962d7.firebaseapp.com',
    storageBucket: 'smartspend-962d7.firebasestorage.app',
    measurementId: 'G-GSN4C5PWYE',
  );

}